# Generated by Django 4.2 on 2023-05-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features2", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UploadedFile",
            new_name="MyForm",
        ),
    ]
