# Generated by Django 4.2 on 2023-05-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features2", "0002_rename_uploadedfile_myform"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MyForm",
            new_name="MyFormModel",
        ),
    ]
