# Generated by Django 4.2 on 2023-05-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features2", "0003_rename_myform_myformmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="myformmodel",
            name="file_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
