# Generated by Django 4.2 on 2023-05-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_alter_feedback_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="rate",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="subject",
            field=models.TextField(),
        ),
    ]
