# Generated by Django 4.2 on 2023-05-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_alter_feedback_rate_alter_feedback_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="rate",
            field=models.PositiveIntegerField(
                choices=[(1, "*"), (2, "**"), (3, "***"), (4, "****"), (5, "*****")]
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="subject",
            field=models.CharField(max_length=255),
        ),
    ]
