# Generated by Django 4.2 on 2023-05-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_alter_feedback_rate_alter_feedback_subject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="body",
            new_name="message",
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rate",
            field=models.IntegerField(),
        ),
    ]
