# Generated by Django 4.2 on 2023-05-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0005_rename_body_feedback_message_alter_feedback_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="rate",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
