# Generated by Django 4.2 on 2023-05-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0004_alter_profile_bio_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
